name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: alpine-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: Check out
      uses: actions/checkout@v1
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Build Scanner
      run: ./_do_build_scanner
    - name: Build Server
      run: ./_do_build_server
